### ISSUE TITLE
Max frequency offset with gmskframesync and ofdmframesync?

### ISSUE THREAD

**Issue by glv2** [jgaeddert/liquid-dsp#279]
Hi,
From tests I made, it looks like ```gmskframesync``` and ```ofdmframesync``` are not able to recover frames when their center frequency is at an offset greater than 1% of the signal bandwidth from the correct center frequency used to create the frames.
Is there a way to increase this maximum offset (for example to 5% or 10%), or not?

**Comment by jgaeddert** [comment]
Yes. The `gmskframesync` uses a `detector_cccf` instance which is used to specify its allowable carrier frequency offset estimate. You can modify this offset [when it is created](https://github.com/jgaeddert/liquid-dsp/blob/master/src/framing/src/gmskframesync.c#L200-L201). The downside here is that the computational complexity will increase as it's now having to search over a larger space.

The `ofdmframesync` object works very differently from the single-carrier framing objects (such as `gmskframesync`) and uses a frequency-domain method for detection instead of the traditional auto-correlation time-domain method which is susceptible to interference. Expanding the frequency offset range here would require more work.
