### ISSUE TITLE
Error attempting "make examples" 

### ISSUE THREAD

**Issue by AndresChoza** [jgaeddert/liquid-dsp#284]
Hi, I've already run the "make" command as I was having trouble before but now I cannot run the "make examples" command supposedly because of some undefined references to functions contained in "math.h":

![image](https://user-images.githubusercontent.com/46696957/168643330-99db8ec7-ca18-4468-8bb7-ac784d292ba5.png)

Any tips?

**Comment by jgaeddert** [comment]
You're seeing a linker error. It's not finding the math library. I suspect you have it installed but it isn't in your path. What do you get when you run the following?

    gcc --print-file-name=libm.a

**Comment by AndresChoza** [comment]
Hi there.

I get the following:

> choza@chozaUbuntu:~/Documents/liquid-dsp$ gcc --print-file-name=libm.a
/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libm.a

I tried to modify the makefile so that the "-lm" linker flag was specifically at the end like this:

![image](https://user-images.githubusercontent.com/46696957/169072316-d3276ee0-ff2d-4492-92a0-b311924d9872.png)

Now I don't get the error reported above, but instead I'm getting this while trying out "make examples": 

![image](https://user-images.githubusercontent.com/46696957/169072678-df747296-2da9-4eee-8ef7-6df2068934d3.png)

**Comment by AndresChoza** [comment]
Also, since we're on the same "trouble with make" page, I'm having trouble building the docs with "make doc".

![image](https://user-images.githubusercontent.com/46696957/169149114-34785279-1e44-4761-aec0-e714dad90974.png)

Could these be related to each other?

**Comment by jgaeddert** [comment]
1. Your modifications to the makefile aren't really correct (they imply that `-lm` is a dependency on the objects), but it seems as though `make` throws together the compiler/linker commands in the right order to get this to work.
  1. The undefined references to the `fec` library are a result from its interface having changed. If you can live without convolutional & Reed Solomon codes, you might try to compile without them. I can help with this.
  1. This is questionable. I haven't bundled documentation with liquid since v1.2.0 (about 10 years ago)

**Comment by AndresChoza** [comment]
Right, so what can I do to fix the 'make doc' command? I'm in need of this documentation

Thanks beforehand.

**Comment by jgaeddert** [comment]
The documentation is not part of the main repository, but is built in https://liquidsdr.org
