### ISSUE TITLE
Liquid DSP - CPFSK 

### ISSUE THREAD

**Issue by JasleenKaur2308** [jgaeddert/liquid-dsp#330]
What is the procedure for symbol synchronization in case of CPFSK demodulation ? 
link  - https://github.com/jgaeddert/liquid-dsp/blob/master/examples/cpfskmodem_example.c

**Comment by jgaeddert** [comment]
As with a lot of things in digital communications, synchronization depends on the specifics of the waveform.

Is the transmission a burst? If so, then try to correlate against a known preamble. If not, and the signal is continuous (e.g. on for a very long duration), then you'll need a tracking loop similar to the [symbol synchronizer](https://liquidsdr.org/doc/symsync/), but for CPFSK. This would recover both timing and carrier phase information.

Of course the implementation would be heavily dependent upon the modulation index, pulse shaping filter, and other parameters. The dimensionality for this is pretty large, so there is no "one size fits all" solution which is why there isn't an easy implementation in liquid for this.
